# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vector = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [3]:
values = np.arange(10, 50)
values


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
 values_shape = np.shape(values)

5. Print the type of the previous array in question 3

In [5]:
print(type(values))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.17.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ahmed/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ahmed/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ahmed/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ahmed/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ahmed/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ahmed/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/ahmed/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/ahmed/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [7]:
print(np.ndim(values))

1


8. Create a boolean array with all the True values

In [8]:
trues = np.ones(10)
trues = (trues > 0)

9. Create a two dimensional array




In [9]:
array_2dim = np.array([[1, 2], [3, 4]])
array_2dim


array([[1, 2],
       [3, 4]])

10. Create a three dimensional array



In [10]:
array_3dim = np.random.rand(3, 2, 3)
print(array_3dim)
print(np.ndim(array_3dim))

[[[0.34254823 0.41296196 0.11770509]
  [0.36921727 0.76573143 0.95284747]]

 [[0.90913081 0.19713883 0.04457366]
  [0.21794262 0.03346153 0.20585598]]

 [[0.64669374 0.18218273 0.73036889]
  [0.08036862 0.35254765 0.08710824]]]
3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
reverse_array = np.flip(values)
print(reverse_array)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
new_array = np.zeros(10)
new_array[4] = 1
print(new_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
id_matrix = np.identity(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype("float")

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
product = arr1*arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comparator = arr1 > arr2


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr = np.arange(0, 10)
arr_odd = []
for i in arr:
    if i%2 != 0:
        arr_odd.append(i)
arr_odd = np.array(arr_odd)

18. Replace all odd numbers to -1 from previous array

In [18]:
indexes = np.where(arr % 2 !=0)
for index in indexes:
    arr[index] = -1

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
indexes = (5, 6, 7, 8)
for index in indexes:
    arr[index] = 12

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
square = np.ones((3, 3))
square[1, 1] = 0

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 5, 9]])
arr2d[1, 1] = 12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# converting first row entries to 64
arr3d[0,0, :] = 64

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
values = np.arange(0, 10)
values = values.reshape((5, 2))
firstarray = values[0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
values = np.arange(0, 10)
values = values.reshape((2, 5))
secondarry = values[1]
value = secondarry[1]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
values = np.arange(0, 10)
values = values.reshape(2, 5)
extracted_values = values[:, 2].reshape(2, 1)

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
values = np.random.random_sample((10, 10))
print(values)
maxinum = np.max(values)
minimum = np.min(values)
print(maxinum, minimum)

[[0.91948539 0.48518545 0.01102088 0.00688536 0.85981089 0.92441706
  0.3824742  0.69958013 0.71467904 0.52037484]
 [0.90049045 0.30698384 0.37136204 0.09153025 0.98736264 0.73856211
  0.11441182 0.81283087 0.89710357 0.35335998]
 [0.09152768 0.91574028 0.52712381 0.95261631 0.80152531 0.34367868
  0.67374738 0.78240691 0.32792851 0.9435734 ]
 [0.9729325  0.4471869  0.06460133 0.06657219 0.133929   0.42880108
  0.17350771 0.01498962 0.62985198 0.43945915]
 [0.51206416 0.59951789 0.35799133 0.9138288  0.881102   0.91971117
  0.29659063 0.2317213  0.07377585 0.41066365]
 [0.43748508 0.71491254 0.92100864 0.21153778 0.18810821 0.40132175
  0.42192377 0.12642745 0.86195072 0.88475308]
 [0.34032221 0.27693384 0.92744311 0.71108256 0.05182504 0.44344663
  0.98453379 0.1660002  0.88734664 0.10413607]
 [0.69250264 0.18410338 0.636945   0.30865806 0.94941131 0.365574
  0.69136201 0.417962   0.39425755 0.29593529]
 [0.48185574 0.88932653 0.36976524 0.56687123 0.68508341 0.0205533
  0.03245273 0.

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.where(a == b)
common_value = a[common]

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.where(a == b)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
notwill_index = np.where(names != 'Will')
refined_data = data[notwill_index]

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
refined_data = []
for element in names:
    if element != "Will" and element != "Joe":
        index = np.where(names == element)
        refined_data.append(data[index])
refined_data = np.array(refined_data)

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
values = np.random.random_sample(15)
values = values*15
arr = values.reshape(5, 3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
values = np.random.random_sample(16)
values = values*16
arr = values.reshape(2, 2, 4)
print(arr)

[[[ 1.05331014 13.98875132 14.3418909   1.80765903]
  [ 8.37074952 14.70813929 15.37547619 10.39582853]]

 [[ 0.87826653  4.30211622  0.25211957 11.20924032]
  [ 0.73345012  6.43218624  1.3494485   7.14337473]]]


33. Swap axes of the array you created in Question 32

In [33]:
arr = arr.reshape(4, 2, 2)
arr

array([[[ 1.05331014, 13.98875132],
        [14.3418909 ,  1.80765903]],

       [[ 8.37074952, 14.70813929],
        [15.37547619, 10.39582853]],

       [[ 0.87826653,  4.30211622],
        [ 0.25211957, 11.20924032]],

       [[ 0.73345012,  6.43218624],
        [ 1.3494485 ,  7.14337473]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
values = np.random.randn(10)
print("Values : \n", values)
sqrt_values = np.sqrt(values)
sqrt_values = np.where(sqrt_values < 0.5, 0, sqrt_values)

Values : 
 [ 0.16958466 -0.54616951 -1.39356925  0.66168259 -0.10994096  1.51828372
  1.39866627 -0.12351694  1.3869824  -0.40047901]


/home/ahmed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until
/home/ahmed/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in less
  after removing the cwd from sys.path.


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.randn(12)
print(arr1)
arr2 = np.random.randn(12)
print(arr2)
arr3 = np.where(arr1 > arr2, arr1, arr2)

[ 0.51606144 -0.3874099  -0.62395717 -1.79872025 -1.07618747 -0.57479942
 -0.48417993  0.85887227 -0.7209615   0.10934264 -0.95930758  1.62423988]
[-0.81488283 -0.2761396   1.88328531 -1.722524    0.11664431  0.39194597
 -0.03631831 -0.49767579 -0.41258862  1.42350826  1.46286153 -0.3874443 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sep = np.unique(names)
sep = np.sort(sep)

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
for element in a:
    if element in b:
        a = np.delete(a, np.where(a == element))
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:, 1] = newColumn

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [44]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
result = x.dot(y)
result

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [42]:
values = np.random.randn(20)
sumaiton = np.cumsum(values)
sumaiton

array([-0.86505024, -0.80696949, -1.01984534, -0.4784474 , -0.64448308,
        0.37123108, -0.13427779, -1.16382696, -0.65099665, -0.38616287,
        0.12627599, -0.32398527, -0.54191822,  0.28641495, -0.03382674,
       -0.09787137, -0.30103325, -0.08211767, -1.4245656 , -2.53811884])