# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
import numpy as np
array_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = array_1.reshape(2,5)

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [14]:
array_2 = np.ones((2, 5))
array_2
np.vstack((array_1, array_2))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
np.hstack((array_1, np.zeros((2, 3))))

array([[0., 1., 2., 3., 4., 0., 0., 0.],
       [5., 6., 7., 8., 9., 0., 0., 0.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [17]:
np.ravel(array_1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [18]:
np.ravel(array_2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
array_1d = np.arange(0, 15)
array_2d = np.reshape(array_1d, (5, 3))
array_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
fiveArray = np.random.randint(10, size = (5, 5))
squared = np.square(fiveArray)

[[2 1 8 9 5]
 [9 2 3 9 3]
 [1 2 7 9 7]
 [6 8 6 0 4]
 [6 2 2 7 7]]


array([[ 4,  1, 64, 81, 25],
       [81,  4,  9, 81,  9],
       [ 1,  4, 49, 81, 49],
       [36, 64, 36,  0, 16],
       [36,  4,  4, 49, 49]])

## Question:8

### Create 5x6 an array and find the mean?

In [29]:
array1 = np.random.randint(10, size = (5, 6))
avg = np.mean(array1)
print(array1)

[[5 5 9 9 7 3]
 [7 4 0 2 6 6]
 [8 2 5 8 1 7]
 [7 2 2 0 9 6]
 [3 1 3 0 5 6]]
4.6


## Question:9

### Find the standard deviation of the previous array in Q8?

In [31]:
dev = np.std(array1)

2.8118795611950858


## Question:10

### Find the median of the previous array in Q8?

In [32]:
med = np.median(array1)

## Question:11

### Find the transpose of the previous array in Q8?

In [33]:
array1_t = np.transpose(array1)
array1_t

array([[5, 7, 8, 7, 3],
       [5, 4, 2, 2, 1],
       [9, 0, 5, 2, 3],
       [9, 2, 8, 0, 0],
       [7, 6, 1, 9, 5],
       [3, 6, 7, 6, 6]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
array_4 = np.random.randint(5, size=(4, 4))
d_sum = np.sum(np.diagonal(array_4))
d_sum

## Question:13

### Find the determinant of the previous array in Q12?

In [39]:
det_array4 = np.linalg.det(array_4)
det_array4

-80.99999999999996

## Question:14

### Find the 5th and 95th percentile of an array?

In [40]:
fifth = np.percentile(array_4, 5)
nith = np.percentile(array_4, 95)
print(fifth, nith)

0.0 4.0


## Question:15

### How to find if a given array has any null values?

In [41]:
nulls = np.isnan(array_4)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])